/**
 * Search-engine crawler detection, driven purely by the request User-Agent.
 *
 * FitMess is phone-only: `src/middleware.ts` redirects every non-mobile
 * visitor to the "open it on your phone" gate. That gate is correct for a
 * human on a laptop, but it is fatal for search indexing — most crawlers
 * fetch with a desktop-shaped User-Agent, so they were served a 307 to
 * `/samo-za-telefon` for *every* URL, including `/robots.txt` and
 * `/sitemap.xml`. The result: fitmess.app could not be indexed at all.
 *
 * Note that Google's *primary* crawler is the smartphone Googlebot, whose UA
 * carries an "Android … Mobile Safari" token and therefore already passes
 * `isMobileUserAgent`. But the `robots.txt` fetcher, the sitemap fetcher, the
 * Search Console verification/inspection fetchers, and the desktop Googlebot
 * variant all use UAs with no mobile token — which is exactly what this
 * check catches.
 *
 * Crawlers matched here are served the same content a phone visitor gets, so
 * this is not cloaking: the gate is skipped, nothing else changes.
 */
const CRAWLER_UA =
  /bot|crawl|spider|slurp|bingpreview|google-inspectiontool|google-site-verification|chrome-lighthouse|facebookexternalhit|facebookcatalog|twitterbot|linkedinbot|whatsapp|telegrambot|discordbot|embedly|quora link preview|pinterest|redditbot|applebot|duckduckbot|yandex|baiduspider|petalbot|ia_archiver/i;

export function isCrawlerUserAgent(userAgent: string | null | undefined): boolean {
  if (!userAgent) return false;
  return CRAWLER_UA.test(userAgent);
}

/**
 * Well-known files that must be reachable by *any* client, with no gate and
 * no session work — regardless of User-Agent.
 *
 * `/robots.txt` and `/sitemap.xml` are generated by the Next metadata routes
 * in `src/app/robots.ts` / `src/app/sitemap.ts`. Neither is matched by the
 * middleware's static-asset exclusion (they carry no image extension), so
 * without this allowlist they were redirected to the phone gate: Google saw a
 * redirect where robots.txt should be, and Search Console could not fetch the
 * sitemap.
 */
const CRAWLER_PATHS: readonly string[] = [
  "/robots.txt",
  "/sitemap.xml",
  "/opengraph-image",
  "/.well-known/assetlinks.json",
  "/.well-known/apple-app-site-association",
];

export function isCrawlerPath(pathname: string): boolean {
  return CRAWLER_PATHS.includes(pathname);
}
