import type { MetadataRoute } from "next";

import { PUBLIC_LEGAL_PATHS } from "@/lib/legal/paths";

/**
 * `/robots.txt` — generated by Next's metadata route convention.
 *
 * FitMess is a mostly-private PWA: everything behind auth (`/danas`,
 * `/analitika`, `/dodaj/*`, `/agent`, `/profil`, `/admin`), the API route
 * handlers, and the auth/onboarding plumbing carry no public value and must
 * never surface in search. Only the public marketing surface — the landing
 * page (`/`) and the pre-auth questionnaire (`/upitnik`) — is left crawlable.
 * The disallow list mirrors the private routes enumerated in
 * `src/lib/auth/route-protection.ts`.
 *
 * `metadataBase` (set in `layout.tsx`) resolves the absolute sitemap/host URLs.
 */
const SITE_URL = "https://fitmess.app";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        // Public, indexable surface only. The legal documents belong here and
        // not behind the disallow list: both stores link to them from the
        // listing, and a policy URL that search engines are told to ignore
        // reads as one that is not meant to be found. That covers the Serbian
        // originals, their fixed-English renderings under `/en`, and the
        // English-word aliases that redirect to the originals — a crawler that
        // is told not to fetch `/privacy` never learns it points at
        // `/privatnost`, so the redirect passes nothing along.
        allow: [
          "/",
          "/upitnik",
          ...PUBLIC_LEGAL_PATHS,
        ],
        // Everything auth-gated or internal — kept out of the index.
        disallow: [
          "/danas",
          "/analitika",
          "/dodaj",
          "/agent",
          "/profil",
          "/admin",
          "/api/",
          "/auth/",
          "/onboarding",
          "/telefon",
          "/prijava",
          "/registracija",
          "/zaboravljena-lozinka",
          "/nova-lozinka",
          "/nemas-pristup",
          "/samo-za-telefon",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
